#!/usr/bin/env bash

# Define variables
WEB_01_IP="54.83.87.119"
WEB_02_IP="18.204.231.167"
LB_IP="18.208.223.205"

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Edit the HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg >/dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 $WEB_01_IP:80 check
    server web-02 $WEB_02_IP:80 check
EOF

# Enable HAProxy service to start on boot
sudo systemctl enable haproxy

# Restart HAProxy service
sudo systemctl restart haproxy

echo "HAProxy installation and configuration completed."
